export const XLARGE_PAPER_BOTTOM_OFFSET = 48;
export const XLARGE_PAPER_TOP_OFFSET = 48;
export const XLARGE_PAPER_SIDE_OFFSET = 80;

export const PAPER_BOTTOM_OFFSET = 48;
export const PAPER_TOP_OFFSET = 48;
export const PAPER_SIDE_OFFSET = 48;

export const SMALL_PAPER_BOTTOM_OFFSET = 24;
export const SMALL_PAPER_TOP_OFFSET = 48;
export const SMALL_PAPER_SIDE_OFFSET = 24;

export const XLARGE_HEADER_TOP_OFFSET = 24;
export const XLARGE_HEADER_LEFT_OFFSET = 48;
export const XLARGE_HEADER_RIGHT_OFFSET = 80;

export const HEADER_TOP_OFFSET = 24;
export const HEADER_LEFT_OFFSET = 48;
export const HEADER_RIGHT_OFFSET = 24;

export const SMALL_HEADER_TOP_OFFSET = 16;
export const SMALL_HEADER_LEFT_OFFSET = 24;
export const SMALL_HEADER_RIGHT_OFFSET = 24;

export const TIMELINE_STRADDLED_LEFT_WIDTH = 150;
export const TIMELINE_POINTER_SIZE = 8;
export const TIMELINE_GUTTER_WIDTH = 24;
